language: python
branches:
  only:
  - master
  - dev
  - "/^release-.*$/"
python:
  - "3.6"
install:
- pip install pipenv
- pipenv install --dev
script:
- python setup.py test
deploy:
  provider: pypi
  user: wqy
  on:
    branch: master
  distributions: sdist bdist_wheel
  skip_existing: true
  password:
    secure: RpJnstXCJrIS8vf1lwKGF+y88wsN9hxOrUdIcsGdppoAWa0OuBaE9wQ8yWIqTPR5UAn1kCATEMhEbGZEU618gqEEG0dyLHCzlCujH8uIqPdWdtSMDJIgi68d3ytJni+ubdICDTUQcs1LggLJkFrMgqNAhXtenuUs5aVQkPLrgVGPGBUuTHZLkwXTLxgdtQiqOaRxPSEl/x64OFPps4+TwCpW3l6Xt4Y5vghJ8ET+tnP3DavIlFm0+nUaTtHNFR372C7Dcgf8RFRYvuavS0rKkZuTMiwwvVusHH9++Pi0PVtOXWxtIF5EZBA+yr8O/4tBaI0a6vbbs3jYzkiODULMyFzSAQJ/p3paURwLDlBKyVByB/aL+OMkXqVeiAN6mv8PdFQ/sx5Fn1IosdzusQnWgHyboe0HIs8rr11NSaRMnhEexd2StEqLa2BF/uLDmv7+dFM5Iqxu/S1dZoOYU8n3kAUKS8kXz6zaFDBbge4jc+r8q2P4xAIz017MuJ+dS745CnhCtPMD/OA9erHb7E23xDZpM7p+C56WDIiH08KO4MT3eueT/ZVIpq2F0wn92yuc45DyY6gBs8MmXNfL1n+6bZfYAOYQRApHy6LaiQ9H14QxWVWT1lJUbGqhRUaUkzS2J9+JSEnpYMhIAFkg0d4tJubx5E2ewNQsSYEL3c32Mmw=
